### ISSUE TITLE
AttributeError for jobstats on running jobs

### ISSUE THREAD

**Issue by andrewsanchez** [nauhpc/jobstats#12]
```bash
aas229@wind $ jobstats -r
JobID JobName ReqMem MaxRSS ReqCPUS UserCPU Timelimit Elapsed State JobEff
==============================================================================================================
Traceback (most recent call last):
File "/common/bin/jobstats", line 702, in <module>
main()
File "/common/bin/jobstats", line 437, in main
maxRSS = maxRSS.replace(letter, '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

When maxrss is unavailable, it is set to `None` here: https://github.com/nauhpc/jobstats/blob/5010accda6c092d1f6b47a401e8047d32458618a/jobstats/jobstats#L103-L110

In the current implementation of `jobstats`, setting maxrss to `str(0)` would prevent this error.

**Comment by yfoo** [comment]
Thanks Andrew, we took care of this!
